### ISSUE TITLE
syntax error on activation

### ISSUE THREAD

**Issue by fernandofunicelli** [Jevuska/stt2-extension-add-terms#1]
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in wp-content/plugins/stt2-extension-add-terms-master/lib/includes/functions.php on line 178

**Comment by Jevuska** [comment]
The code is working well. This code about how to increase and decrease manually `meta_value`,`meta_count` as hits counter in table stt2_meta of your database, Please check your SEO SearchTerms Tagging 2 plugin and database.
